files:
  - source: /tms-next-intl-crowdin/messages/en.json
    translation: /tms-next-intl-crowdin/messages/%two_letters_code%.json
  - source: /tms-react-i18next-crowdin/src/locales/en.json
    translation: /tms-react-i18next-crowdin/src/locales/%two_letters_code%.json
